"""PPO policy training from self-play decision records (SOT-1689).

Learns the small policy+value MLP that :class:`agents.ppo_agent.PPOAgent` plays,
from the JSONL decision records of the SOT-1688 self-play pipeline
(:mod:`eval.selfplay`, schema ``ume-selfplay-v1``), and writes the weights to
``data/policy.json`` (schema ``ume-policy-v1``, see :mod:`agents.policy_net`).

**Local training tool only.** This is the one place numpy is allowed (see the
training-only section of ``requirements.txt``); nothing under ``agents/`` may
import it. The pure-Python forward in :mod:`agents.policy_net` and the numpy
forward here implement the same math and must stay in lockstep.

Algorithm
---------
Vanilla PPO: clipped surrogate objective + GAE(γ, λ), Adam, a value-MSE head and
an entropy bonus, over K epochs of minibatches per update. The training loop
(scaled up by SOT-1695: multi-deck rotation, RuleAgent sparring mix,
per-iteration evaluation with a best-iteration promotion gate and stagnation
early-stop; SOT-1699 adds **opponent-pool "league" self-play** — sparring vs a
bounded FIFO of past-policy snapshots, learner-side records only — and bounded
**reward shaping** — potential-based prize-differential + a deck-out/no-active
loss penalty, both applied at training time so the stored records stay
schema-valid ±1/0):

1. play ``--games-per-iter`` matches with the *current* policy through
   :func:`eval.selfplay.run_selfplay` — mirror games (optionally rotating the
   ``--deck-dir`` decks) plus a ``--sparring-frac`` share vs the RuleAgent
   baseline (each iteration's records are kept as a JSONL under ``--data-dir``
   — the same audited pipeline/schema as SOT-1688);
2. rebuild trajectories per ``(game, player)``; the reward is 0 everywhere and
   the terminal ±1/0 on a trajectory's last decision;
3. recompute values and the acting policy's log-probs from the stored features
   under the **pre-update snapshot** (the records were generated by exactly
   these weights, so the recomputation *is* π_old — no schema change needed);
4. run the clipped PPO update and save the artifact.

Records train the distribution of a decision's **first chosen option index**
(``action_index``) — the exact quantity :func:`agents.policy_net.sample_action`
samples via Gumbel top-k. Decisions with no real choice (``n_options < 2``),
empty actions, or an index beyond the slot head are skipped.

再学習可能: ``--init-from`` resumes from an existing ``policy.json``, and
``--bootstrap-data`` warm-starts from any existing record file (e.g. the
SOT-1688 rule-mirror acceptance data) before the self-play iterations — with
π_old recomputed under the current weights this is an advantage-weighted
imitation update, useful to escape the random init. ``--iters 0`` with
``--bootstrap-data`` is therefore a pure offline (engine-free) training run.

CLI::

    venv/bin/python train/ppo.py --iters 6 --games-per-iter 32 \
        --bootstrap-data eval/selfplay_runs/acceptance_sot1688.jsonl \
        --out data/policy.json
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
from typing import Optional

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO not in sys.path:
    sys.path.insert(0, REPO)

import numpy as np  # noqa: E402  (training-only dependency)

from agents.features import FEATURE_DIM, FEATURE_VERSION  # noqa: E402
from agents.policy_net import N_SLOTS, POLICY_SCHEMA, validate_policy  # noqa: E402

__all__ = [
    "init_params",
    "params_to_policy",
    "policy_to_params",
    "forward_np",
    "masked_log_softmax_np",
    "load_records",
    "build_batch",
    "compute_gae",
    "ppo_update",
    "save_policy",
    "main",
]

_MASK_NEG = -1e9  # logit for slots beyond a decision's legal options


# --------------------------------------------------------------------------- #
# Parameters <-> the JSON artifact
# --------------------------------------------------------------------------- #
def init_params(hidden: int, seed: int, n_slots: int = N_SLOTS) -> dict:
    """Small-scale Gaussian init (float64 numpy arrays keyed like the artifact)."""
    rng = np.random.default_rng(seed)

    def w(rows: int, cols: int) -> np.ndarray:
        return rng.normal(0.0, 1.0 / np.sqrt(cols), size=(rows, cols))

    return {
        "w1": w(hidden, FEATURE_DIM),
        "b1": np.zeros(hidden),
        "w2": w(n_slots, hidden) * 0.01,  # near-uniform initial policy
        "b2": np.zeros(n_slots),
        "vw": np.zeros(hidden),
        "vb": np.zeros(()),
    }


def params_to_policy(params: dict, meta: Optional[dict] = None) -> dict:
    """Serialise numpy params to the ``ume-policy-v1`` artifact dict."""
    hidden, _ = params["w1"].shape
    n_slots = params["w2"].shape[0]
    policy = {
        "schema": POLICY_SCHEMA,
        "feature_version": FEATURE_VERSION,
        "feature_dim": FEATURE_DIM,
        "hidden": int(hidden),
        "n_slots": int(n_slots),
        "w1": params["w1"].tolist(),
        "b1": params["b1"].tolist(),
        "w2": params["w2"].tolist(),
        "b2": params["b2"].tolist(),
        "vw": params["vw"].tolist(),
        "vb": float(params["vb"]),
        "meta": meta or {},
    }
    errors = validate_policy(policy)
    if errors:  # a bug here must fail loudly, not ship a broken artifact
        raise ValueError(f"produced an invalid policy artifact: {errors}")
    return policy


def policy_to_params(policy: dict) -> dict:
    """Load an artifact dict back into numpy params (for ``--init-from``)."""
    errors = validate_policy(policy)
    if errors:
        raise ValueError(f"invalid policy artifact: {errors}")
    if policy["feature_version"] != FEATURE_VERSION or policy["feature_dim"] != FEATURE_DIM:
        raise ValueError(
            f"artifact feature layout v{policy['feature_version']}/dim {policy['feature_dim']} "
            f"does not match this code (v{FEATURE_VERSION}/dim {FEATURE_DIM})"
        )
    return {
        "w1": np.asarray(policy["w1"], dtype=float),
        "b1": np.asarray(policy["b1"], dtype=float),
        "w2": np.asarray(policy["w2"], dtype=float),
        "b2": np.asarray(policy["b2"], dtype=float),
        "vw": np.asarray(policy["vw"], dtype=float),
        "vb": np.asarray(float(policy["vb"])),
    }


def save_policy(params: dict, out_path: str, meta: Optional[dict] = None) -> dict:
    """Write the artifact JSON (compact floats keep it repo-committable)."""
    policy = params_to_policy(params, meta)
    out_dir = os.path.dirname(out_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(policy, fh, ensure_ascii=False)
        fh.write("\n")
    return policy


# --------------------------------------------------------------------------- #
# Forward pass (numpy twin of agents.policy_net.forward)
# --------------------------------------------------------------------------- #
def forward_np(params: dict, x: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Batched MLP forward: ``x (N,D) -> (h (N,H), logits (N,S), values (N,))``."""
    h = np.tanh(x @ params["w1"].T + params["b1"])
    logits = h @ params["w2"].T + params["b2"]
    values = h @ params["vw"] + params["vb"]
    return h, logits, values


def masked_log_softmax_np(logits: np.ndarray, n_options: np.ndarray) -> np.ndarray:
    """Row-wise log-softmax over each row's first ``min(n_options, S)`` slots."""
    n_slots = logits.shape[1]
    mask = np.arange(n_slots)[None, :] < np.minimum(n_options, n_slots)[:, None]
    masked = np.where(mask, logits, _MASK_NEG)
    top = masked.max(axis=1, keepdims=True)
    logsumexp = np.log(np.exp(masked - top).sum(axis=1, keepdims=True)) + top
    return np.where(mask, masked - logsumexp, _MASK_NEG)


# --------------------------------------------------------------------------- #
# Records -> training batch
# --------------------------------------------------------------------------- #
def load_records(paths: list[str], n_slots: int = N_SLOTS) -> tuple[list[dict], dict]:
    """Read self-play JSONL files, keeping the PPO-trainable decisions.

    Kept: current schema/feature layout, a real choice (``n_options >= 2``), a
    non-empty action whose first index fits the slot head. Returns the kept
    records and a ``{"read": int, "kept": int, "skipped": {reason: int}}`` tally
    (silent drops would misreport coverage).
    """
    kept: list[dict] = []
    skipped: dict[str, int] = {}
    read = 0

    def skip(reason: str) -> None:
        skipped[reason] = skipped.get(reason, 0) + 1

    for source, path in enumerate(paths):
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                if not line.strip():
                    continue
                read += 1
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    skip("bad_json")
                    continue
                if rec.get("schema") != "ume-selfplay-v1" or rec.get("feature_version") != FEATURE_VERSION:
                    skip("schema_mismatch")
                    continue
                feats = rec.get("features")
                if not isinstance(feats, list) or len(feats) != FEATURE_DIM:
                    skip("bad_features")
                    continue
                if not isinstance(rec.get("n_options"), int) or rec["n_options"] < 2:
                    skip("trivial_choice")
                    continue
                idx = rec.get("action_index")
                if not isinstance(idx, int) or idx < 0:
                    skip("empty_action")
                    continue
                if idx >= n_slots:
                    skip("beyond_slots")
                    continue
                rec["_source"] = source  # game ids are only unique within one file
                kept.append(rec)
    return kept, {"read": read, "kept": len(kept), "skipped": skipped}


def compute_gae(
    rewards: np.ndarray, values: np.ndarray, gamma: float, lam: float
) -> tuple[np.ndarray, np.ndarray]:
    """GAE over one *terminal* trajectory (no bootstrap: V after the end is 0).

    Returns ``(advantages, returns)`` with ``returns = advantages + values``.
    """
    n = len(rewards)
    adv = np.zeros(n)
    last = 0.0
    for t in range(n - 1, -1, -1):
        next_value = values[t + 1] if t + 1 < n else 0.0
        delta = rewards[t] + gamma * next_value - values[t]
        last = delta + gamma * lam * last
        adv[t] = last
    return adv, adv + values


#: cabt end-reason codes for self-inflicted losses (SOT-1699 loss shaping):
#: 2 empty deck (deck-out), 3 no active. Mirrors eval.selfplay._DECKOUT_REASON.
_SELF_LOSS_REASONS = (2, 3)


def _shaped_rewards(
    records: list[dict],
    indices: list[int],
    gamma: float,
    prize_shaping: float,
    loss_shaping: float,
) -> np.ndarray:
    """Terminal ±1/0 reward on one trajectory + optional SOT-1699 shaping.

    * **Prize shaping** (potential-based, policy-invariant): with potential
      ``φ_t = prize_shaping · (opp_remaining − own_remaining) / 6`` (higher when
      the acting player has taken more prizes), each step gets
      ``F_t = γ·φ_{t+1} − φ_t`` (terminal ``φ = 0``). It telescopes to a bounded
      tail, so the terminal ±1 keeps dominating — it only sharpens credit
      assignment toward prize-taking moves. Records lacking the prize fields
      (e.g. old bootstrap data) contribute ``φ = 0`` and are unaffected.
    * **Loss shaping**: a small extra negative on a *loss* ended by deck-out /
      no-active (``end_reason_code`` in :data:`_SELF_LOSS_REASONS`) — nudging the
      policy away from those self-inflicted defeats.
    """
    n = len(indices)
    rewards = np.zeros(n)
    rewards[-1] = float(records[indices[-1]]["reward"])

    if prize_shaping:
        phi = np.zeros(n)
        for k, i in enumerate(indices):
            own, opp = records[i].get("own_prizes"), records[i].get("opp_prizes")
            if isinstance(own, (int, float)) and isinstance(opp, (int, float)) \
                    and not isinstance(own, bool) and not isinstance(opp, bool):
                phi[k] = prize_shaping * (float(opp) - float(own)) / 6.0
        for t in range(n):
            phi_next = phi[t + 1] if t + 1 < n else 0.0
            rewards[t] += gamma * phi_next - phi[t]

    if loss_shaping and rewards[-1] < 0:
        if records[indices[-1]].get("end_reason_code") in _SELF_LOSS_REASONS:
            rewards[-1] -= loss_shaping
    return rewards


def build_batch(
    records: list[dict],
    params: dict,
    gamma: float,
    lam: float,
    *,
    prize_shaping: float = 0.0,
    loss_shaping: float = 0.0,
) -> dict:
    """Trajectories -> flat arrays: features, actions, masks, advantages, returns.

    Values (for GAE) and the acting policy's log-probs (π_old) are recomputed
    from the stored features under ``params`` — the snapshot that generated the
    records — so the record schema needs no logprob/value fields.

    ``prize_shaping`` / ``loss_shaping`` (SOT-1699) add the bounded reward
    shaping described in :func:`_shaped_rewards`; both default to 0.0 (the exact
    terminal-only reward of SOT-1689/1695).
    """
    x = np.asarray([r["features"] for r in records], dtype=float)
    actions = np.asarray([r["action_index"] for r in records], dtype=int)
    n_options = np.asarray([r["n_options"] for r in records], dtype=int)

    _, logits, values = forward_np(params, x)
    logp = masked_log_softmax_np(logits, n_options)
    old_logp = logp[np.arange(len(records)), actions]

    # Group into trajectories: reward 0 until the terminal decision's ±1/0.
    trajectories: dict[tuple, list[int]] = {}
    for i, rec in enumerate(records):
        trajectories.setdefault((rec.get("_source"), rec["game"], rec["player"]), []).append(i)

    advantages = np.zeros(len(records))
    returns = np.zeros(len(records))
    for indices in trajectories.values():
        indices.sort(key=lambda i: records[i]["decision"])
        rewards = _shaped_rewards(records, indices, gamma, prize_shaping, loss_shaping)
        adv, ret = compute_gae(rewards, values[indices], gamma, lam)
        advantages[indices] = adv
        returns[indices] = ret

    std = advantages.std()
    if std > 1e-8:
        advantages = (advantages - advantages.mean()) / std
    return {
        "x": x,
        "actions": actions,
        "n_options": n_options,
        "old_logp": old_logp,
        "advantages": advantages,
        "returns": returns,
        "n_trajectories": len(trajectories),
    }


# --------------------------------------------------------------------------- #
# The PPO update (manual backprop + Adam)
# --------------------------------------------------------------------------- #
def _adam_step(params: dict, grads: dict, state: dict, lr: float) -> None:
    state["t"] += 1
    beta1, beta2, eps = 0.9, 0.999, 1e-8
    t = state["t"]
    for k, g in grads.items():
        state["m"][k] = beta1 * state["m"][k] + (1 - beta1) * g
        state["v"][k] = beta2 * state["v"][k] + (1 - beta2) * g * g
        m_hat = state["m"][k] / (1 - beta1**t)
        v_hat = state["v"][k] / (1 - beta2**t)
        params[k] = params[k] - lr * m_hat / (np.sqrt(v_hat) + eps)


def _grads_and_losses(
    params: dict,
    x: np.ndarray,
    actions: np.ndarray,
    n_options: np.ndarray,
    old_logp: np.ndarray,
    advantages: np.ndarray,
    returns: np.ndarray,
    clip: float,
    value_coef: float,
    entropy_coef: float,
) -> tuple[dict, dict]:
    """One minibatch: clipped-surrogate + value-MSE + entropy losses and grads."""
    n = len(x)
    h, logits, values = forward_np(params, x)
    logp = masked_log_softmax_np(logits, n_options)
    n_slots = logits.shape[1]
    mask = np.arange(n_slots)[None, :] < np.minimum(n_options, n_slots)[:, None]
    probs = np.where(mask, np.exp(logp), 0.0)

    rows = np.arange(n)
    logp_a = logp[rows, actions]
    ratio = np.exp(logp_a - old_logp)
    surr1 = ratio * advantages
    surr2 = np.clip(ratio, 1.0 - clip, 1.0 + clip) * advantages
    policy_loss = -np.minimum(surr1, surr2).mean()
    entropy = -(np.where(mask, probs * logp, 0.0)).sum(axis=1)
    value_err = values - returns
    losses = {
        "policy": float(policy_loss),
        "value": float(value_coef * (value_err**2).mean()),
        "entropy": float(entropy.mean()),
        "clip_frac": float((surr2 < surr1).mean()),
    }

    # d(policy_loss)/d(logp_a): only where the unclipped branch is active.
    unclipped = (surr1 <= surr2).astype(float)
    g_logp_a = -(advantages * ratio * unclipped) / n
    d_logits = g_logp_a[:, None] * (np.eye(n_slots)[actions] - probs)
    # Entropy bonus (loss term −c_e·H): dH/dz = −p·(logp + H).
    d_logits += entropy_coef / n * probs * (np.where(mask, logp, 0.0) + entropy[:, None])
    d_values = 2.0 * value_coef * value_err / n

    d_h = d_logits @ params["w2"] + d_values[:, None] * params["vw"][None, :]
    d_z1 = d_h * (1.0 - h * h)
    grads = {
        "w2": d_logits.T @ h,
        "b2": d_logits.sum(axis=0),
        "vw": h.T @ d_values,
        "vb": np.asarray(d_values.sum()),
        "w1": d_z1.T @ x,
        "b1": d_z1.sum(axis=0),
    }
    return grads, losses


def ppo_update(
    params: dict,
    batch: dict,
    adam: dict,
    *,
    epochs: int = 4,
    minibatch: int = 256,
    lr: float = 3e-4,
    clip: float = 0.2,
    value_coef: float = 0.5,
    entropy_coef: float = 0.01,
    max_grad_norm: float = 0.5,
    seed: int = 0,
) -> dict:
    """Run K epochs of minibatched clipped-PPO on ``batch`` (in-place on params)."""
    rng = np.random.default_rng(seed)
    n = len(batch["x"])
    last_losses: dict = {}
    for _ in range(epochs):
        order = rng.permutation(n)
        for start in range(0, n, minibatch):
            idx = order[start : start + minibatch]
            grads, last_losses = _grads_and_losses(
                params,
                batch["x"][idx],
                batch["actions"][idx],
                batch["n_options"][idx],
                batch["old_logp"][idx],
                batch["advantages"][idx],
                batch["returns"][idx],
                clip,
                value_coef,
                entropy_coef,
            )
            norm = np.sqrt(sum(float((g**2).sum()) for g in grads.values()))
            if norm > max_grad_norm:
                grads = {k: g * (max_grad_norm / norm) for k, g in grads.items()}
            _adam_step(params, grads, adam, lr)
    return last_losses


# --------------------------------------------------------------------------- #
# The self-play training loop
# --------------------------------------------------------------------------- #
def _collect_selfplay(
    params: dict,
    games: int,
    base_seed: int,
    out_path: str,
    *,
    decks: Optional[list] = None,
    sparring_frac: float = 0.0,
    league_frac: float = 0.0,
    snapshots: Optional[list[dict]] = None,
    rng: Optional[random.Random] = None,
) -> dict:
    """One iteration of self-play with the current weights (needs the engine).

    Opponent mix per iteration (fractions of ``games``):

    * **mirror** — current policy vs itself (on-policy, both seats train);
    * **sparring** (``sparring_frac``, SOT-1695) — vs the RuleAgent baseline; the
      rule side's records train as advantage-weighted imitation (π_old recomputed
      under the current weights, exactly like ``--bootstrap-data``);
    * **league** (``league_frac``, SOT-1699) — the learner (current policy) vs an
      opponent sampled from ``snapshots`` (a pool of *past* policy dicts). Only
      the learner's on-policy records are kept (``record_labels={"ppo"}``) — we
      never imitate an old, weaker policy. This trains exploit-resistance against
      a distribution of past selves. When the pool is empty (iteration 0) league
      games fall back to the mirror.

    ``decks`` (from :func:`eval.selfplay.load_deck_dir`) rotates mirror decks per
    game; league games rotate the same pool one deck at a time.
    """
    from agents import PPOAgent, RuleAgent
    from eval.selfplay import run_selfplay

    policy = params_to_policy(params)

    def make(seed: int) -> "PPOAgent":
        return PPOAgent(seed=seed, policy=policy)

    snapshots = list(snapshots or [])
    league = int(round(games * league_frac)) if snapshots else 0
    sparring = int(round(games * sparring_frac))
    league = min(league, max(0, games - sparring))
    mirror = games - sparring - league
    if rng is None:
        rng = random.Random(base_seed)

    summaries = []
    if mirror > 0:
        summaries.append(run_selfplay(
            mirror, out_path, agents=(("ppo", make), ("ppo", make)),
            decks=decks, base_seed=base_seed,
        ))
    if sparring > 0:
        summaries.append(run_selfplay(
            sparring, out_path,
            agents=(("ppo", make), ("rule", lambda seed: RuleAgent(seed=seed))),
            decks=decks, base_seed=base_seed + 2 * mirror,
        ))
    for g in range(league):
        snap = snapshots[rng.randrange(len(snapshots))]

        def make_opp(seed: int, snap=snap) -> "PPOAgent":
            return PPOAgent(seed=seed, policy=snap)

        # Alternate which seat the on-policy learner takes so its records cover
        # both seats across the league block.
        learner = ("ppo", make)
        opponent = ("league", make_opp)
        agents = (learner, opponent) if g % 2 == 0 else (opponent, learner)
        g_decks = [decks[g % len(decks)]] if decks else None
        summaries.append(run_selfplay(
            1, out_path, agents=agents, decks=g_decks,
            base_seed=base_seed + 2 * (mirror + sparring + g),
            record_labels={"ppo"},
        ))

    combined = {
        "games": sum(s["games"] for s in summaries),
        "decisions": sum(s["decisions"] for s in summaries),
        "faults": sum(s["faults"] for s in summaries),
        "invalid_records": sum(s["invalid_records"] for s in summaries),
        "draws": sum(s["draws"] for s in summaries),
        "undecided": sum(s["undecided"] for s in summaries),
        "wins": {},
        "mirror_games": mirror,
        "sparring_games": sparring,
        "league_games": league,
    }
    for s in summaries:
        for label, w in s["wins"].items():
            combined["wins"][label] = combined["wins"].get(label, 0) + w
    return combined


def _evaluate(params: dict, n: int, seed: int) -> dict:
    """In-memory paired arena of the current weights vs RuleAgent / RandomAgent.

    The per-iteration evaluation log (SOT-1695): PPOAgent carrying the live
    params, ``n`` side-swapped matches per opponent on the champion deck,
    nothing written to disk. Returns ``{"vs_rule": {...}, "vs_random": {...}}``
    with win rate + Wilson 95% CI + faults per opponent.
    """
    from agents import PPOAgent, RandomAgent, RuleAgent
    from eval.arena import _load_deck, run_arena
    from eval.trace import RecordLevel

    policy = params_to_policy(params)
    deck = _load_deck("deck.csv")
    out = {}
    for key, make_b in (("vs_rule", lambda s: RuleAgent(seed=s)),
                        ("vs_random", lambda s: RandomAgent(seed=s))):
        report = run_arena(
            lambda s: PPOAgent(seed=s, policy=policy),
            make_b,
            deck0=deck,
            n_matches=n,
            side_swap=True,
            agent_seed=seed,
            label_a="ppo",
            label_b=key,
            record_traces=False,
            trace_level=RecordLevel.RESULT,
            write_outputs=False,
        )
        wr = report.win_rates
        out[key] = {
            "n": report.totals["n"],
            "win_rate": wr["a_win_rate"],
            "ci95": list(wr["a_win_rate_ci95"]),
            "faults": report.safety["a_faults"],
        }
    return out


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="PPO training over ume-selfplay-v1 records -> data/policy.json."
    )
    parser.add_argument("--iters", type=int, default=6,
                        help="self-play PPO iterations (0 = offline bootstrap only)")
    parser.add_argument("--games-per-iter", type=int, default=32,
                        help="self-play matches per iteration")
    parser.add_argument("--deck-dir", default=None,
                        help="rotate mirror decks over every *.csv here (SOT-1695, "
                             "e.g. decks/initial); default: deck.csv only")
    parser.add_argument("--sparring-frac", type=float, default=0.0,
                        help="fraction of each iteration's games played vs the "
                             "RuleAgent sparring baseline instead of the mirror")
    parser.add_argument("--league-frac", type=float, default=0.0,
                        help="fraction of each iteration's games played by the "
                             "learner vs a sampled past-policy snapshot (SOT-1699 "
                             "opponent-pool / league learning; 0 = off)")
    parser.add_argument("--league-pool-size", type=int, default=5,
                        help="max past-policy snapshots kept in the league pool "
                             "(oldest dropped; needs --league-frac)")
    parser.add_argument("--prize-shaping", type=float, default=0.0,
                        help="coefficient of the potential-based prize-differential "
                             "reward shaping (SOT-1699; 0 = terminal reward only)")
    parser.add_argument("--loss-shaping", type=float, default=0.0,
                        help="extra negative reward on a deck-out / no-active loss "
                             "(SOT-1699; 0 = off)")
    parser.add_argument("--eval-games", type=int, default=0,
                        help="per-iteration evaluation matches vs RuleAgent and vs "
                             "Random (0 = no eval, keep every iteration's weights)")
    parser.add_argument("--patience", type=int, default=0,
                        help="stop after this many iterations without a new best "
                             "vs-rule eval win rate (0 = never; needs --eval-games)")
    parser.add_argument("--bootstrap-data", action="append", default=[],
                        help="existing record JSONL(s) for warm-start updates (repeatable)")
    parser.add_argument("--bootstrap-passes", type=int, default=3,
                        help="PPO update passes over the bootstrap data")
    parser.add_argument("--init-from", default=None,
                        help="resume from an existing policy.json (再学習)")
    parser.add_argument("--out", default="data/policy.json", help="artifact output path")
    parser.add_argument("--data-dir", default="eval/selfplay_runs/ppo",
                        help="directory for per-iteration self-play JSONLs")
    parser.add_argument("--hidden", type=int, default=64, help="hidden layer width")
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--clip", type=float, default=0.2)
    parser.add_argument("--gamma", type=float, default=0.99)
    parser.add_argument("--lam", type=float, default=0.95)
    parser.add_argument("--epochs", type=int, default=4, help="PPO epochs per update")
    parser.add_argument("--minibatch", type=int, default=256)
    parser.add_argument("--value-coef", type=float, default=0.5)
    parser.add_argument("--entropy-coef", type=float, default=0.01)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args(argv)

    if args.init_from:
        with open(args.init_from, encoding="utf-8") as fh:
            params = policy_to_params(json.load(fh))
        print(f"resumed params from {args.init_from}")
    else:
        params = init_params(args.hidden, args.seed)
    adam = {
        "t": 0,
        "m": {k: np.zeros_like(v) for k, v in params.items()},
        "v": {k: np.zeros_like(v) for k, v in params.items()},
    }
    hyper = dict(
        epochs=args.epochs, minibatch=args.minibatch, lr=args.lr, clip=args.clip,
        value_coef=args.value_coef, entropy_coef=args.entropy_coef,
    )
    history: list[dict] = []

    def update_from(paths: list[str], phase: str, passes: int = 1) -> None:
        records, tally = load_records(paths)
        if not records:
            print(f"{phase}: no trainable records in {paths} ({tally})")
            return
        for p in range(passes):
            batch = build_batch(
                records, params, args.gamma, args.lam,
                prize_shaping=args.prize_shaping, loss_shaping=args.loss_shaping,
            )
            losses = ppo_update(params, batch, adam, seed=args.seed + p, **hyper)
            entry = {
                "phase": phase, "pass": p, "records": tally["kept"],
                "skipped": tally["skipped"], "trajectories": batch["n_trajectories"],
                **losses,
            }
            history.append(entry)
            print(json.dumps(entry, ensure_ascii=False))

    if args.bootstrap_data:
        update_from(args.bootstrap_data, "bootstrap", passes=args.bootstrap_passes)

    decks = None
    if args.deck_dir:
        from eval.selfplay import load_deck_dir

        decks = load_deck_dir(args.deck_dir)

    # Promotion gate (SOT-1695): with per-iteration eval on, the *best* eval
    # iteration's snapshot ships, not the last — ranked by vs-rule win rate,
    # tie-broken by vs-random. The pre-iteration weights (bootstrap output,
    # iteration -1) compete too, so an eval-degrading run cannot ship a
    # regression.
    eval_history: list[dict] = []
    best: Optional[dict] = None

    def evaluate_and_track(iteration: int) -> None:
        nonlocal best
        if args.eval_games <= 0:
            return
        scores = _evaluate(params, args.eval_games, args.seed + 77_000 + 1000 * (iteration + 1))
        entry = {"phase": "eval", "iter": iteration, **scores}
        eval_history.append(entry)
        print(json.dumps(entry, ensure_ascii=False))
        key = (scores["vs_rule"]["win_rate"], scores["vs_random"]["win_rate"])
        if best is None or key > best["key"]:
            best = {
                "key": key,
                "iter": iteration,
                "params": {k: np.array(v, copy=True) for k, v in params.items()},
                "scores": scores,
            }

    evaluate_and_track(-1)

    # League opponent pool (SOT-1699): a bounded FIFO of *past* policy snapshots
    # the learner spars against. Grown after each iteration's update so the pool
    # at iteration ``it`` holds the snapshots of iterations ``< it``.
    league_pool: list[dict] = []
    league_rng = random.Random(args.seed + 999)

    def push_snapshot() -> None:
        if args.league_frac > 0:
            league_pool.append(params_to_policy(params))
            if len(league_pool) > max(1, args.league_pool_size):
                del league_pool[0]

    stopped_early = None
    for it in range(args.iters):
        out_jsonl = os.path.join(args.data_dir, f"iter_{it:03d}.jsonl")
        os.makedirs(args.data_dir, exist_ok=True)
        if os.path.exists(out_jsonl):  # run_selfplay appends; keep iterations clean
            os.remove(out_jsonl)
        summary = _collect_selfplay(
            params, args.games_per_iter, args.seed + 10_000 * (it + 1), out_jsonl,
            decks=decks, sparring_frac=args.sparring_frac,
            league_frac=args.league_frac, snapshots=league_pool, rng=league_rng,
        )
        print(json.dumps({"phase": "selfplay", "iter": it, **{
            k: summary[k] for k in ("games", "decisions", "faults", "invalid_records",
                                    "wins", "draws", "undecided",
                                    "mirror_games", "sparring_games", "league_games")
        }}, ensure_ascii=False))
        if summary["faults"] or summary["invalid_records"]:
            print(f"iteration {it}: faults/invalid records present — aborting")
            return 1
        update_from([out_jsonl], f"iter_{it:03d}")
        push_snapshot()  # add this iteration's weights to the league pool
        evaluate_and_track(it)
        if best is not None and args.patience > 0 and it - best["iter"] >= args.patience:
            stopped_early = {"iter": it, "best_iter": best["iter"], "patience": args.patience}
            print(json.dumps({"phase": "early_stop", **stopped_early}, ensure_ascii=False))
            break
        save_policy(
            best["params"] if best is not None else params, args.out,
            meta=_meta(args, it + 1, history, eval_history, best, stopped_early, decks),
        )

    final_params = best["params"] if best is not None else params
    save_policy(final_params, args.out,
                meta=_meta(args, args.iters, history, eval_history, best, stopped_early, decks))
    print(f"wrote policy -> {args.out}")
    return 0


def _meta(
    args: argparse.Namespace,
    iters_done: int,
    history: list[dict],
    eval_history: Optional[list[dict]] = None,
    best: Optional[dict] = None,
    stopped_early: Optional[dict] = None,
    decks: Optional[list] = None,
) -> dict:
    meta = {
        "issue": "SOT-1699",
        "iters_done": iters_done,
        "games_per_iter": args.games_per_iter,
        "bootstrap_data": args.bootstrap_data,
        "hidden": args.hidden,
        "lr": args.lr,
        "clip": args.clip,
        "gamma": args.gamma,
        "lam": args.lam,
        "epochs": args.epochs,
        "entropy_coef": args.entropy_coef,
        "seed": args.seed,
        "updates": len(history),
        "records_trained": sum(h.get("records", 0) for h in history),
        "last_losses": {k: v for k, v in (history[-1] if history else {}).items()
                        if k in ("policy", "value", "entropy", "clip_frac")},
        "deck_dir": args.deck_dir,
        "n_decks": len(decks) if decks else 1,
        "sparring_frac": args.sparring_frac,
        "league_frac": args.league_frac,
        "league_pool_size": args.league_pool_size,
        "prize_shaping": args.prize_shaping,
        "loss_shaping": args.loss_shaping,
        "eval_games": args.eval_games,
        "patience": args.patience,
    }
    if eval_history:
        meta["eval_history"] = eval_history
    if best is not None:
        meta["best_iter"] = best["iter"]
        meta["best_eval"] = best["scores"]
    if stopped_early is not None:
        meta["stopped_early"] = stopped_early
    return meta


if __name__ == "__main__":
    raise SystemExit(main())
